### ISSUE TITLE
iRobot Create 2 Incorporation 

### ISSUE THREAD

**Issue by JordanD7** [urastogi885/roomba-robot#1]
Is this only for simulation purposes or can I use this and upload the wall following to an actual iRobot Create 2?

**Comment by urastogi885** [comment]
I would say only for simulation purposes. You will need to modify the code a bit to get it working on a real robot. But, you can start by reducing the linear velocity.
The repository is more inclined towards creating a robot from scratch in Gazebo.

**Comment by JordanD7** [comment]
Thank you for the information
